## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
application_df.columns
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

#  YOUR CODE GOES HERE
application_df = application_df.drop(columns=['EIN'])

In [3]:
# Check the unique values in the NAME column
name_counts = application_df['NAME'].value_counts()

# Set a threshold for how frequent a name must be to be kept as is
threshold = 50  # You can adjust this number based on your dataset
print(name_counts)

NAME
PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: count, Length: 19568, dtype: int64

In [4]:
# Create a list of names to keep based on frequency
names_to_keep = name_counts[name_counts >= threshold].index.tolist()

# Replace the less frequent names with 'Other'
application_df['NAME_BINNED'] = application_df['NAME'].apply(lambda x: x if x in names_to_keep else 'Other')

# Now drop the original NAME column, as it is binned into 'NAME_BINNED'
application_df = application_df.drop(columns=['NAME'])

In [5]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
unique_values = application_df.nunique()
print(unique_values)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
NAME_BINNED                 52
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 200
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
count = application_df['CLASSIFICATION'].value_counts()
count_greater_than_1 = count[count > 1]

# Display the filtered counts
print(count_greater_than_1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 1000
classification_counts = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = classification_counts[classification_counts <= cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_df_encoded = pd.get_dummies(application_df, drop_first=True)
application_df_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,NAME_BINNED_TOPS CLUB INC,NAME_BINNED_UNITED FEDERATION OF DOLL CLUBS INC,NAME_BINNED_UNITED STATES BOWLING CONGRESS INC,NAME_BINNED_UNIVERSITY OF FLORIDA,NAME_BINNED_UNIVERSITY OF WYOMING,NAME_BINNED_VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY,NAME_BINNED_VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC,NAME_BINNED_WASHINGTON STATE GRANGE,NAME_BINNED_WASHINGTON STATE UNIVERSITY,NAME_BINNED_WORKERS UNITED
0,1,5000,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,108590,1,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1,6692,1,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1,142590,1,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = application_df_encoded.drop(columns=['IS_SUCCESSFUL'])  # Features (exclude target column)
y = application_df_encoded['IS_SUCCESSFUL']  # Target
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=128, activation='relu', input_dim=X_train_scaled.shape[1]))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=48, activation='relu'))

# Third hidden layer (optional)
nn.add(tf.keras.layers.Dense(units=32, activation='relu'))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Check the structure of the model
nn.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 128)            │        11,264 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 48)             │         6,192 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 32)             │         1,568 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,057 (74.44 KB)

 Trainable params: 19,057 (74.44 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(optimizer='adam', 
           loss='binary_crossentropy', 
           metrics=['accuracy'])

In [18]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, 
                   epochs=100,        # Number of epochs (you can adjust this)
)

Epoch 1/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 932us/step - accuracy: 0.7280 - loss: 0.5274
Epoch 2/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 925us/step - accuracy: 0.7651 - loss: 0.4787
Epoch 3/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.7694 - loss: 0.4742
Epoch 4/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 928us/step - accuracy: 0.7667 - loss: 0.4763
Epoch 5/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 922us/step - accuracy: 0.7694 - loss: 0.4725
Epoch 6/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.7701 - loss: 0.4708
Epoch 7/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 932us/step - accuracy: 0.7712 - loss: 0.4685
Epoch 8/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 915us/step - accuracy: 0.7715 - loss: 0.4675
Epoch 9/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 944us/step - accuracy: 0.7698 - loss: 0.4713
Epoch 10/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 938us/step - accuracy: 0.7757 - loss: 0.4658
Epoch 11/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 929us/step - accuracy: 0.7739 - loss: 0.4687
Epoch 12/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 923us/step - accuracy: 0.7725 - loss: 0.4664
Epoch 13/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 921us/step - accuracy: 0.7746 - loss: 0.4641
Epoch 14/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 888us/step - accuracy: 0.7710 - loss: 0.4680
Epoch 15/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 900us/step - accuracy: 0.7710 - loss: 0.4678
Epoch 16/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 954us/step - accuracy: 0.7775 - loss: 0.4629
Epoch 17/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 918us/step - accuracy: 0.7689 - loss: 0.4678
Epoch 18/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 928us/step - accuracy: 0.7777 - loss: 0.4613
Epoch 19/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 910us/step - accuracy: 0.7741 - loss: 0.4643
Epoch 20/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 941us/step - accuracy: 0.7762 - loss: 0.4614
Epoch 21/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.7774 - loss: 0.4615
Epoch 22/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 923us/step - accuracy: 0.7721 - loss: 0.4640
Epoch 23/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 937us/step - accuracy: 0.7734 - loss: 0.4608
Epoch 24/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 920us/step - accuracy: 0.7778 - loss: 0.4568
Epoch 25/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 897us/step - accuracy: 0.7744 - loss: 0.4644
Epoch 26/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 930us/step - accuracy: 0.7692 - loss: 0.4675
Epoch 27/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 891us/step - accuracy: 0.7765 - loss: 0.4591
Epoch 28/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 895us/step - accuracy: 0.7764 - loss: 0.4583
Epoch 29/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 932us/step - accuracy: 0.7742 - loss: 0.4617
Epoch 30/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 898us/step - accuracy: 0.7735 - loss: 0.4637
Epoch 31/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.7779 - loss: 0.4588
Epoch 32/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 946us/step - accuracy: 0.7760 - loss: 0.4598
Epoch 33/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 902us/step - accuracy: 0.7714 - loss: 0.4639
Epoch 34/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 933us/step - accuracy: 0.7764 - loss: 0.4604
Epoch 35/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 973us/step - accuracy: 0.7777 - loss: 0.4564
Epoch 36/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 921us/step - accuracy: 0.7789 - loss: 0.4554
Epoch 37/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 924us/step - accuracy: 0.7775 - loss: 0.4587
Epoch 38/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 940us/step - accuracy: 0.7753 - loss: 0.4591
Epoch 39/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - accuracy: 0.7769 - loss: 0.4603
Epoch 40/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 937us/step - accuracy: 0.7760 - loss: 0.4586
Epoch 41/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 936us/step - accuracy: 0.7750 - loss: 0.4610
Epoch 42/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 895us/step - accuracy: 0.7793 - loss: 0.4548
Epoch 43/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 913us/step - accuracy: 0.7742 - loss: 0.4632
Epoch 44/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 931us/step - accuracy: 0.7801 - loss: 0.4535
Epoch 45/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 922us/step - accuracy: 0.7755 - loss: 0.4593
Epoch 46/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 919us/step - accuracy: 0.7727 - loss: 0.4620
Epoch 47/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 920us/step - accuracy: 0.7731 - loss: 0.4587
Epoch 48/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 936us/step - accuracy: 0.7771 - loss: 0.4556
Epoch 49/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 919us/step - accuracy: 0.7767 - loss: 0.4538
Epoch 50/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 931us/step - accuracy: 0.7773 - loss: 0.4556
Epoch 51/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 958us/step - accuracy: 0.7791 - loss: 0.4536
Epoch 52/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 954us/step - accuracy: 0.7793 - loss: 0.4547
Epoch 53/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7762 - loss: 0.4561
Epoch 54/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7772 - loss: 0.4569
Epoch 55/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7791 - loss: 0.4536
Epoch 56/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7753 - loss: 0.4569
Epoch 57/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7794 - loss: 0.4544
Epoch 58/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 984us/step - accuracy: 0.7743 - loss: 0.4613
Epoch 59/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7822 - loss: 0.4518
Epoch 60/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7771 - loss: 0.4537
Epoch 61/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7781 - loss: 0.4534
Epoch 62/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7771 - loss: 0.4562
Epoch 63/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7748 - loss: 0.4588
Epoch 64/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7776 - loss: 0.4535
Epoch 65/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7802 - loss: 0.4501
Epoch 66/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7766 - loss: 0.4563
Epoch 67/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 995us/step - accuracy: 0.7736 - loss: 0.4625
Epoch 68/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7811 - loss: 0.4505
Epoch 69/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7800 - loss: 0.4502
Epoch 70/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7740 - loss: 0.4556
Epoch 71/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7801 - loss: 0.4530
Epoch 72/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7782 - loss: 0.4553
Epoch 73/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 972us/step - accuracy: 0.7780 - loss: 0.4500
Epoch 74/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7782 - loss: 0.4541
Epoch 75/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7769 - loss: 0.4549
Epoch 76/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7798 - loss: 0.4546
Epoch 77/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7798 - loss: 0.4545
Epoch 78/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 989us/step - accuracy: 0.7775 - loss: 0.4539
Epoch 79/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7768 - loss: 0.4562
Epoch 80/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 994us/step - accuracy: 0.7762 - loss: 0.4555
Epoch 81/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7821 - loss: 0.4498
Epoch 82/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 989us/step - accuracy: 0.7767 - loss: 0.4543
Epoch 83/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7781 - loss: 0.4546
Epoch 84/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7781 - loss: 0.4545
Epoch 85/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7810 - loss: 0.4517
Epoch 86/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7813 - loss: 0.4490
Epoch 87/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7818 - loss: 0.4504
Epoch 88/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7767 - loss: 0.4566
Epoch 89/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7745 - loss: 0.4598
Epoch 90/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7795 - loss: 0.4517
Epoch 91/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7815 - loss: 0.4522
Epoch 92/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7803 - loss: 0.4523
Epoch 93/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7799 - loss: 0.4510
Epoch 94/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 998us/step - accuracy: 0.7777 - loss: 0.4530
Epoch 95/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7775 - loss: 0.4531
Epoch 96/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7746 - loss: 0.4590
Epoch 97/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 960us/step - accuracy: 0.7765 - loss: 0.4535
Epoch 98/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 964us/step - accuracy: 0.7788 - loss: 0.4513
Epoch 99/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 995us/step - accuracy: 0.7762 - loss: 0.4555
Epoch 100/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 996us/step - accuracy: 0.7779 - loss: 0.4524

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - 1ms/step - accuracy: 0.7569 - loss: 0.5147
Loss: 0.5146825909614563, Accuracy: 0.756851315498352

In [ ]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save('AlphabetSoupCharity_Optimization.h5')

print("Model saved to 'model.h5'")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Model saved to 'model.h5'